version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/myapp1

hooks:
  BeforeInstall:
    - location: src/before_install.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: src/after_install.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: src/start_application.sh
      timeout: 300
      runas: root

  ApplicationStop:
    - location: src/stop_application.sh
      timeout: 300
      runas: root
